# Generated by Django 5.2.13 on 2026-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_course_chapter_topic_studentperformance_chapter_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='cgpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='credit_hours',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='sgpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
